class Autogenerated {
  List<String> labelsDias;
  List<String> labelsSemanas;
  String sId;
  Geral geral;
  Sudeste sudeste;
  Nordeste nordeste;
  Sul sul;
  CentroOeste centroOeste;
  Norte norte;
  String createdAt;
  String updatedAt;
  int iV;

  Autogenerated(
      {this.labelsDias,
      this.labelsSemanas,
      this.sId,
      this.geral,
      this.sudeste,
      this.nordeste,
      this.sul,
      this.centroOeste,
      this.norte,
      this.createdAt,
      this.updatedAt,
      this.iV});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    labelsDias = json['labelsDias'].cast<String>();
    labelsSemanas = json['labelsSemanas'].cast<String>();
    sId = json['_id'];
    geral = json['geral'] != null ? new Geral.fromJson(json['geral']) : null;
    sudeste =
        json['Sudeste'] != null ? new Sudeste.fromJson(json['Sudeste']) : null;
    nordeste = json['Nordeste'] != null
        ? new Nordeste.fromJson(json['Nordeste'])
        : null;
    sul = json['Sul'] != null ? new Sul.fromJson(json['Sul']) : null;
    centroOeste = json['Centro-Oeste'] != null
        ? new CentroOeste.fromJson(json['Centro-Oeste'])
        : null;
    norte = json['Norte'] != null ? new Norte.fromJson(json['Norte']) : null;
    createdAt = json['created_at'];
    updatedAt = json['updated_at'];
    iV = json['__v'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['labelsDias'] = this.labelsDias;
    data['labelsSemanas'] = this.labelsSemanas;
    data['_id'] = this.sId;
    if (this.geral != null) {
      data['geral'] = this.geral.toJson();
    }
    if (this.sudeste != null) {
      data['Sudeste'] = this.sudeste.toJson();
    }
    if (this.nordeste != null) {
      data['Nordeste'] = this.nordeste.toJson();
    }
    if (this.sul != null) {
      data['Sul'] = this.sul.toJson();
    }
    if (this.centroOeste != null) {
      data['Centro-Oeste'] = this.centroOeste.toJson();
    }
    if (this.norte != null) {
      data['Norte'] = this.norte.toJson();
    }
    data['created_at'] = this.createdAt;
    data['updated_at'] = this.updatedAt;
    data['__v'] = this.iV;
    return data;
  }
}

class Geral {
  SP sP;
  SP mG;
  SP bA;
  SP rJ;
  SP cE;
  SP sC;
  SP gO;
  SP pA;
  SP rS;
  SP pR;
  SP dF;
  SP mA;
  SP pE;
  SP aM;
  SP eS;
  SP mT;
  SP pB;
  SP pI;
  SP aL;
  SP sE;
  SP mS;
  SP rN;
  SP tO;
  SP rO;
  SP rR;
  SP aP;
  SP aC;

  Geral(
      {this.sP,
      this.mG,
      this.bA,
      this.rJ,
      this.cE,
      this.sC,
      this.gO,
      this.pA,
      this.rS,
      this.pR,
      this.dF,
      this.mA,
      this.pE,
      this.aM,
      this.eS,
      this.mT,
      this.pB,
      this.pI,
      this.aL,
      this.sE,
      this.mS,
      this.rN,
      this.tO,
      this.rO,
      this.rR,
      this.aP,
      this.aC});

  Geral.fromJson(Map<String, dynamic> json) {
    sP = json['SP'] != null ? new SP.fromJson(json['SP']) : null;
    mG = json['MG'] != null ? new SP.fromJson(json['MG']) : null;
    bA = json['BA'] != null ? new SP.fromJson(json['BA']) : null;
    rJ = json['RJ'] != null ? new SP.fromJson(json['RJ']) : null;
    cE = json['CE'] != null ? new SP.fromJson(json['CE']) : null;
    sC = json['SC'] != null ? new SP.fromJson(json['SC']) : null;
    gO = json['GO'] != null ? new SP.fromJson(json['GO']) : null;
    pA = json['PA'] != null ? new SP.fromJson(json['PA']) : null;
    rS = json['RS'] != null ? new SP.fromJson(json['RS']) : null;
    pR = json['PR'] != null ? new SP.fromJson(json['PR']) : null;
    dF = json['DF'] != null ? new SP.fromJson(json['DF']) : null;
    mA = json['MA'] != null ? new SP.fromJson(json['MA']) : null;
    pE = json['PE'] != null ? new SP.fromJson(json['PE']) : null;
    aM = json['AM'] != null ? new SP.fromJson(json['AM']) : null;
    eS = json['ES'] != null ? new SP.fromJson(json['ES']) : null;
    mT = json['MT'] != null ? new SP.fromJson(json['MT']) : null;
    pB = json['PB'] != null ? new SP.fromJson(json['PB']) : null;
    pI = json['PI'] != null ? new SP.fromJson(json['PI']) : null;
    aL = json['AL'] != null ? new SP.fromJson(json['AL']) : null;
    sE = json['SE'] != null ? new SP.fromJson(json['SE']) : null;
    mS = json['MS'] != null ? new SP.fromJson(json['MS']) : null;
    rN = json['RN'] != null ? new SP.fromJson(json['RN']) : null;
    tO = json['TO'] != null ? new SP.fromJson(json['TO']) : null;
    rO = json['RO'] != null ? new SP.fromJson(json['RO']) : null;
    rR = json['RR'] != null ? new SP.fromJson(json['RR']) : null;
    aP = json['AP'] != null ? new SP.fromJson(json['AP']) : null;
    aC = json['AC'] != null ? new SP.fromJson(json['AC']) : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.sP != null) {
      data['SP'] = this.sP.toJson();
    }
    if (this.mG != null) {
      data['MG'] = this.mG.toJson();
    }
    if (this.bA != null) {
      data['BA'] = this.bA.toJson();
    }
    if (this.rJ != null) {
      data['RJ'] = this.rJ.toJson();
    }
    if (this.cE != null) {
      data['CE'] = this.cE.toJson();
    }
    if (this.sC != null) {
      data['SC'] = this.sC.toJson();
    }
    if (this.gO != null) {
      data['GO'] = this.gO.toJson();
    }
    if (this.pA != null) {
      data['PA'] = this.pA.toJson();
    }
    if (this.rS != null) {
      data['RS'] = this.rS.toJson();
    }
    if (this.pR != null) {
      data['PR'] = this.pR.toJson();
    }
    if (this.dF != null) {
      data['DF'] = this.dF.toJson();
    }
    if (this.mA != null) {
      data['MA'] = this.mA.toJson();
    }
    if (this.pE != null) {
      data['PE'] = this.pE.toJson();
    }
    if (this.aM != null) {
      data['AM'] = this.aM.toJson();
    }
    if (this.eS != null) {
      data['ES'] = this.eS.toJson();
    }
    if (this.mT != null) {
      data['MT'] = this.mT.toJson();
    }
    if (this.pB != null) {
      data['PB'] = this.pB.toJson();
    }
    if (this.pI != null) {
      data['PI'] = this.pI.toJson();
    }
    if (this.aL != null) {
      data['AL'] = this.aL.toJson();
    }
    if (this.sE != null) {
      data['SE'] = this.sE.toJson();
    }
    if (this.mS != null) {
      data['MS'] = this.mS.toJson();
    }
    if (this.rN != null) {
      data['RN'] = this.rN.toJson();
    }
    if (this.tO != null) {
      data['TO'] = this.tO.toJson();
    }
    if (this.rO != null) {
      data['RO'] = this.rO.toJson();
    }
    if (this.rR != null) {
      data['RR'] = this.rR.toJson();
    }
    if (this.aP != null) {
      data['AP'] = this.aP.toJson();
    }
    if (this.aC != null) {
      data['AC'] = this.aC.toJson();
    }
    return data;
  }
}

class SP {
  List<Semana> semana;
  List<dynamic> dias;

  SP({this.semana, this.dias});

  SP.fromJson(Map<String, dynamic> json) {
    if (json['semana'] != null) {
      semana = [];
      json['semana'].forEach((v) {
        semana.add(new Semana.fromJson(v));
      });
    }
    if (json['dias'] != null) {
      dias = [];
      json['dias'].forEach((v) {
        //dias.add(new Dias.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.semana != null) {
      data['semana'] = this.semana.map((v) => v.toJson()).toList();
    }
    if (this.dias != null) {
      data['dias'] = this.dias.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class Semana {
  String sId;
  int casosAcumulado;
  int obitosAcumulado;

  Semana({this.sId, this.casosAcumulado, this.obitosAcumulado});

  Semana.fromJson(Map<String, dynamic> json) {
    sId = json['_id'];
    casosAcumulado = json['casosAcumulado'];
    obitosAcumulado = json['obitosAcumulado'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['_id'] = this.sId;
    data['casosAcumulado'] = this.casosAcumulado;
    data['obitosAcumulado'] = this.obitosAcumulado;
    return data;
  }
}

class Sudeste {
  var sP;
  var mG;
  var rJ;
  var eS;

  Sudeste({
    this.sP,
    this.mG,
    this.rJ,
    this.eS,
  });

  Sudeste.fromJson(Map<String, dynamic> json) {
    sP = json['SP'] != null ? new SP.fromJson(json['SP']) : null;
    mG = json['MG'] != null ? new SP.fromJson(json['MG']) : null;
    rJ = json['RJ'] != null ? new SP.fromJson(json['RJ']) : null;
    eS = json['ES'] != null ? new SP.fromJson(json['ES']) : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.sP != null) {
      data['SP'] = this.sP.toJson();
    }
    if (this.mG != null) {
      data['MG'] = this.mG.toJson();
    }
    if (this.rJ != null) {
      data['RJ'] = this.rJ.toJson();
    }
    if (this.eS != null) {
      data['ES'] = this.eS.toJson();
    }
    return data;
  }
}

class Nordeste {
  SP bA;
  SP cE;
  SP mA;
  SP pE;
  SP pB;
  SP pI;
  SP aL;
  SP sE;
  SP rN;

  Nordeste(
      {this.bA,
      this.cE,
      this.mA,
      this.pE,
      this.pB,
      this.pI,
      this.aL,
      this.sE,
      this.rN});

  Nordeste.fromJson(Map<String, dynamic> json) {
    bA = json['BA'] != null ? new SP.fromJson(json['BA']) : null;
    cE = json['CE'] != null ? new SP.fromJson(json['CE']) : null;
    mA = json['MA'] != null ? new SP.fromJson(json['MA']) : null;
    pE = json['PE'] != null ? new SP.fromJson(json['PE']) : null;
    pB = json['PB'] != null ? new SP.fromJson(json['PB']) : null;
    pI = json['PI'] != null ? new SP.fromJson(json['PI']) : null;
    aL = json['AL'] != null ? new SP.fromJson(json['AL']) : null;
    sE = json['SE'] != null ? new SP.fromJson(json['SE']) : null;
    rN = json['RN'] != null ? new SP.fromJson(json['RN']) : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.bA != null) {
      data['BA'] = this.bA.toJson();
    }
    if (this.cE != null) {
      data['CE'] = this.cE.toJson();
    }
    if (this.mA != null) {
      data['MA'] = this.mA.toJson();
    }
    if (this.pE != null) {
      data['PE'] = this.pE.toJson();
    }
    if (this.pB != null) {
      data['PB'] = this.pB.toJson();
    }
    if (this.pI != null) {
      data['PI'] = this.pI.toJson();
    }
    if (this.aL != null) {
      data['AL'] = this.aL.toJson();
    }
    if (this.sE != null) {
      data['SE'] = this.sE.toJson();
    }
    if (this.rN != null) {
      data['RN'] = this.rN.toJson();
    }
    return data;
  }
}

class Sul {
  SP sC;
  SP rS;
  SP pR;

  Sul({this.sC, this.rS, this.pR});

  Sul.fromJson(Map<String, dynamic> json) {
    sC = json['SC'] != null ? new SP.fromJson(json['SC']) : null;
    rS = json['RS'] != null ? new SP.fromJson(json['RS']) : null;
    pR = json['PR'] != null ? new SP.fromJson(json['PR']) : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.sC != null) {
      data['SC'] = this.sC.toJson();
    }
    if (this.rS != null) {
      data['RS'] = this.rS.toJson();
    }
    if (this.pR != null) {
      data['PR'] = this.pR.toJson();
    }
    return data;
  }
}

class CentroOeste {
  SP gO;
  SP dF;
  SP mT;
  SP mS;

  CentroOeste({this.gO, this.dF, this.mT, this.mS});

  CentroOeste.fromJson(Map<String, dynamic> json) {
    gO = json['GO'] != null ? new SP.fromJson(json['GO']) : null;
    dF = json['DF'] != null ? new SP.fromJson(json['DF']) : null;
    mT = json['MT'] != null ? new SP.fromJson(json['MT']) : null;
    mS = json['MS'] != null ? new SP.fromJson(json['MS']) : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.gO != null) {
      data['GO'] = this.gO.toJson();
    }
    if (this.dF != null) {
      data['DF'] = this.dF.toJson();
    }
    if (this.mT != null) {
      data['MT'] = this.mT.toJson();
    }
    if (this.mS != null) {
      data['MS'] = this.mS.toJson();
    }
    return data;
  }
}

class Norte {
  SP pA;
  SP aM;
  SP tO;
  SP rO;
  SP rR;
  SP aP;
  SP aC;

  Norte({this.pA, this.aM, this.tO, this.rO, this.rR, this.aP, this.aC});

  Norte.fromJson(Map<String, dynamic> json) {
    pA = json['PA'] != null ? new SP.fromJson(json['PA']) : null;
    aM = json['AM'] != null ? new SP.fromJson(json['AM']) : null;
    tO = json['TO'] != null ? new SP.fromJson(json['TO']) : null;
    rO = json['RO'] != null ? new SP.fromJson(json['RO']) : null;
    rR = json['RR'] != null ? new SP.fromJson(json['RR']) : null;
    aP = json['AP'] != null ? new SP.fromJson(json['AP']) : null;
    aC = json['AC'] != null ? new SP.fromJson(json['AC']) : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.pA != null) {
      data['PA'] = this.pA.toJson();
    }
    if (this.aM != null) {
      data['AM'] = this.aM.toJson();
    }
    if (this.tO != null) {
      data['TO'] = this.tO.toJson();
    }
    if (this.rO != null) {
      data['RO'] = this.rO.toJson();
    }
    if (this.rR != null) {
      data['RR'] = this.rR.toJson();
    }
    if (this.aP != null) {
      data['AP'] = this.aP.toJson();
    }
    if (this.aC != null) {
      data['AC'] = this.aC.toJson();
    }
    return data;
  }
}
