/* class Autogenerated {
  Confirmados confirmados;
  Obitos obitos;
  String dtUpdated;
  Planilha planilha;

  Autogenerated({
    this.confirmados,
    this.obitos,
    this.dtUpdated,
    this.planilha,
  });

  Autogenerated.fromJson(Map<String, dynamic> json) {
    confirmados = json['confirmados'] != null
        ? new Confirmados.fromJson(json['confirmados'])
        : null;
    obitos =
        json['obitos'] != null ? new Obitos.fromJson(json['obitos']) : null;
    dtUpdated = json['dt_updated'];
    planilha = json['planilha'] != null
        ? new Planilha.fromJson(json['planilha'])
        : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.confirmados != null) {
      data['confirmados'] = this.confirmados.toJson();
    }
    if (this.obitos != null) {
      data['obitos'] = this.obitos.toJson();
    }
    data['dt_updated'] = this.dtUpdated;
    if (this.planilha != null) {
      data['planilha'] = this.planilha.toJson();
    }
    return data;
  }
}
 */

class Confirmados {
  String total;
  String titulo;
  int novos;
  String incidencia;
  String recuperados;
  String acompanhamento;
  String percent;

  Confirmados({
    this.total,
    this.titulo,
    this.novos,
    this.incidencia,
    this.recuperados,
    this.acompanhamento,
    this.percent,
  });

  Confirmados.fromJson(Map<String, dynamic> json) {
    total = json['total'];
    titulo = json['titulo'];
    novos = json['novos'];
    incidencia = json['incidencia'];
    recuperados = json['recuperados'];
    acompanhamento = json['acompanhamento'];
    percent = json['percent'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['total'] = this.total;
    data['titulo'] = this.titulo;
    data['novos'] = this.novos;
    data['incidencia'] = this.incidencia;
    data['recuperados'] = this.recuperados;
    data['acompanhamento'] = this.acompanhamento;
    data['percent'] = this.percent;
    return data;
  }
}

class Obitos {
  String total;
  String titulo;
  int novos;
  String incidencia;
  String letalidade;
  String mortalidade;
  String percent;

  Obitos(
      {this.total,
      this.titulo,
      this.novos,
      this.incidencia,
      this.letalidade,
      this.mortalidade,
      this.percent});

  Obitos.fromJson(Map<String, dynamic> json) {
    total = json['total'];
    titulo = json['titulo'];
    novos = json['novos'];
    incidencia = json['incidencia'];
    letalidade = json['letalidade'];
    mortalidade = json['mortalidade'];
    percent = json['percent'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['total'] = this.total;
    data['titulo'] = this.titulo;
    data['novos'] = this.novos;
    data['incidencia'] = this.incidencia;
    data['letalidade'] = this.letalidade;
    data['mortalidade'] = this.mortalidade;
    data['percent'] = this.percent;
    return data;
  }
}

class Planilha {
  String usuario;
  String nome;
  String usuarioId;
  String status;
  Arquivo arquivo;
  String createdAt;
  String updatedAt;
  String objectId;

  Planilha(
      {this.usuario,
      this.nome,
      this.usuarioId,
      this.status,
      this.arquivo,
      this.createdAt,
      this.updatedAt,
      this.objectId});

  Planilha.fromJson(Map<String, dynamic> json) {
    usuario = json['usuario'];
    nome = json['nome'];
    usuarioId = json['usuario_id'];
    status = json['status'];
    arquivo =
        json['arquivo'] != null ? new Arquivo.fromJson(json['arquivo']) : null;
    createdAt = json['createdAt'];
    updatedAt = json['updatedAt'];
    objectId = json['objectId'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['usuario'] = this.usuario;
    data['nome'] = this.nome;
    data['usuario_id'] = this.usuarioId;
    data['status'] = this.status;
    if (this.arquivo != null) {
      data['arquivo'] = this.arquivo.toJson();
    }
    data['createdAt'] = this.createdAt;
    data['updatedAt'] = this.updatedAt;
    data['objectId'] = this.objectId;
    return data;
  }
}

class Arquivo {
  String sType;
  String name;
  String url;

  Arquivo({this.sType, this.name, this.url});

  Arquivo.fromJson(Map<String, dynamic> json) {
    sType = json['__type'];
    name = json['name'];
    url = json['url'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['__type'] = this.sType;
    data['name'] = this.name;
    data['url'] = this.url;
    return data;
  }
}
